### ISSUE TITLE
Criar Front-end

### ISSUE THREAD

**Issue by Felizolinha** [Felizolinha/treinamento-react#1]
## Criar Front-end
Criar uma tela de login com todas as funcionalidades básicas, com um aviso dizendo se o login foi um sucesso ou não.

## Description
A tela de login precisa permitir que o usuário coloque seu username(ou e-mail), sua senha, um botão para finalizar o login e também precisa conter um alerta indicando o sucesso(ou não) do login.

## Tasks
- [ ] Criar campo de username
- [ ] Criar campo de senha
- [ ] Criar botão de finalizar login
- [ ] Criar alerta de sucesso ou falha do login
- [ ] Estilizar a tela
- [ ] Comunicar com o backend
