### ISSUE TITLE
Criar Back-end

### ISSUE THREAD

**Issue by LuizPettengill** [Felizolinha/treinamento-react#2]
Criar uma API de Login e registrar e guardar os usuários em um banco de dados.

## Description

Criar o CRUD do Login com end points respectivos para cada ação no banco de dados. Cada end point deve retornar erros bem documentados caso alguma dessas ações falhe.

## Tasks
- [x] Inicializar projeto NODE
- [x] Criar estrutura de diretórios do projeto
- [x] Documentar rotas
- [x] Criar rota de Login
- [x] Criar rota de cadastro
- [x] Criar rota de edição de usuário
- [x] Criar rota de deletar conta
- [x] Criar banco de dados
- [x] Fazer CRUD do banco de dados
- [x] Implementar funcionalidade da rota de cadastro
- [x] Implementar funcionalidade da rota de Login
- [x] Implementar funcionalidade da rota de adição de usuário
- [x] Implementar funcionalidade da rota de deletar conta

**Comment by Felizolinha** [comment]
A estrutura dos diretórios não pode ser criada por enquanto porque as pastas precisam de arquivos pra subir para o git.
