### ISSUE TITLE
Testar front-end

### ISSUE THREAD

**Issue by Felizolinha** [Felizolinha/treinamento-react#3]
Fazer testes diversos no front-end

## Description
Realizar testes unitários, de integração e de UI.

## Tasks
- [ ] Estudar testes unitários
- [ ] Estudar testes de integração
- [ ] Estudar testes de UI cross-platform no React
- [ ] Fazer testes unitários
- [ ] Fazer testes de integração
- [ ] Fazer testes de UI
