### ISSUE TITLE
Estudar testes

### ISSUE THREAD

**Issue by Felizolinha** [Felizolinha/treinamento-react#5]
Fazer testes diversos no front-end

## Description
Estudar testes unitários, de integração e de UI.

## Tasks
- [ ] Estudar testes unitários
- [ ] Estudar testes de integração
- [ ] Estudar testes de UI cross-platform no React
